/*
 * @Author: ZHONG JUN
 * @Date: 2020-03-14 00:36:48
 * @Description:
 */

let areas = [
  { code: "11", name: "北京市" },
  { code: "12", name: "天津市" },
  { code: "13", name: "河北省" },
  { code: "14", name: "山西省" },
  { code: "15", name: "内蒙古自治区" },
  { code: "21", name: "辽宁省" },
  { code: "22", name: "吉林省" },
  { code: "23", name: "黑龙江省" },
  { code: "31", name: "上海市" },
  { code: "32", name: "江苏省" },
  { code: "33", name: "浙江省" },
  { code: "34", name: "安徽省" },
  { code: "35", name: "福建省" },
  { code: "36", name: "江西省" },
  { code: "37", name: "山东省" },
  { code: "41", name: "河南省" },
  { code: "42", name: "湖北省" },
  { code: "43", name: "湖南省" },
  { code: "44", name: "广东省" },
  { code: "45", name: "广西壮族自治区" },
  { code: "46", name: "海南省" },
  { code: "50", name: "重庆市" },
  { code: "51", name: "四川省" },
  { code: "52", name: "贵州省" },
  { code: "53", name: "云南省" },
  { code: "54", name: "西藏自治区" },
  { code: "61", name: "陕西省" },
  { code: "62", name: "甘肃省" },
  { code: "63", name: "青海省" },
  { code: "64", name: "宁夏回族自治区" },
  { code: "65", name: "新疆维吾尔自治区" },
  { code: "71", name: "台湾地区" },
  { code: "81", name: "香港特别行政区" },
  { code: "82", name: "澳门特别行政区" },
  { code: "91", name: "国外" },
];
areas = areas.map(e => ({ label: e.name, value: e.name }));

// 民族
const ethnics = [
  '汉族',
  '壮族',
  '回族',
  '满族',
  '土家族',
  '瑶族',
  '苗族',
  '侗族',
  '畲族',
  '蒙古族',
  '藏族',
  '维吾尔族',
  '彝族',
  '布依族',
  '朝鲜族',
  '白族',
  '哈尼族',
  '哈萨克族',
  '傣族',
  '黎族',
  '傈僳族',
  '佤族',
  '高山族',
  '拉祜族',
  '水族',
  '东乡族',
  '纳西族',
  '景颇族',
  '柯尔克孜族',
  '土族',
  '达斡尔族',
  '仫佬族',
  '羌族',
  '布朗族',
  '撒拉族',
  '毛南族',
  '仡佬族',
  '锡伯族',
  '阿昌族',
  '普米族',
  '塔吉克族',
  '怒族',
  '乌孜别克族',
  '俄罗斯族',
  '鄂温克族',
  '德昂族',
  '保安族',
  '裕固族',
  '京族',
  '塔塔尔族',
  '独龙族',
  '鄂伦春族',
  '赫哲族',
  '门巴族',
  '珞巴族',
  '基诺族',
  '其他',
].map(e => ({ label: e, value: e }));;

// 职业种类
const profession = [
  '国家公务员',
  '专业技术人员',
  '企业管理人员',
  '自由职业者',
  '工人',
  '现役军人',
  '个体经营者',
  '职员',
  '农民',
  '学生',
  '退（离）休人员',
  '其他',
].map(e => ({ label: e, value: e }));

// 婚姻状态
const maritalstatus = [
  { label: '已婚', value: 0 },
  { label: '未婚', value: 1 },
  { label: '离异', value: 2 },
  { label: '丧偶', value: 3 },
  { label: '再婚', value: 4 },
];

const illness = [
  '无',
  '妊娠糖尿病',
  '糖尿病',
  '高血压',
  '甲亢',
  'G6PD',
  '肝炎',
  '肺结核',
  '肾炎',
  '风湿',
  '贫血',
  '地中海贫血',
  '癫痫',
  '心脏病',
  '肝脏疾病',
  '肾脏疾病',
];

// 证件类型
const IDType = [
  { label: '二代身份证', value: 0 },
  { label: '港澳台居民居住证', value: 4},
  { label: '回乡证', value: 2},
  { label: '台胞证', value: 3},
  { label: '护照', value: 1},
  { label: '其他', value: 5 },
];

export const basic = {
  description: '基本信息',
  data: [
    {
      id: 'part-1',
      desc: '孕妇个人基本信息1',
      children: [
        {
          id: 'name',
          label: '姓名',
          type: 'text-input',
          charactertype: 'text',
          required: true,
          placeholder: '请输入您的姓名',
        },
        {
          id: 'telephone',
          label: '手机号码',
          type: 'text-input',
          charactertype: 'phone',
          required: true,
        },
        {
          id: 'workPhone',
          label: '固话',
          type: 'text-input',
          charactertype: 'tel',
          required: true,
        },
        {
          id: 'cardNO',
          label: '就诊卡号',
          type: 'text-input',
          charactertype: 'text',
          required: true,
        },
        {
          id: 'zhunshengNO',
          label: '准生证号',
          type: 'text-input',
          charactertype: 'text',
          required: true,
        },
      ],
    },
    {
      id: 'part-2',
      desc: '孕妇个人基本信息2',
      children: [
        {
          id: 'idType',
          label: '证件类型',
          type: 'picker',
          required: true,
          cols: 1,
          data: IDType,
          valueFormat: 'number',
        },
        {
          id: 'idNO',
          label: '证件号码',
          type: 'text-input',
          charactertype: 'text',
          required: true,
        },
        {
          id: 'dob',
          label: '出生日期',
          type: 'date-picker',
          required: true,
          mode: 'date', // 日期date,时间time,日期+时间datetime,年year,月month
          format: 'YYYY-MM-DD', // 显示格式
          valueFormat: 'string', // 返回value值格式
          minDate: new Date(1960, 1, 1, 0, 0, 0),
          maxDate: new Date()
        },
        {
          id: 'age',
          label: '年龄',
          type: 'text-input',
          charactertype: 'digit',
          required: true,
        },
        {
          id: 'nationality',
          label: '国籍',
          type: 'text-input',
          charactertype: 'text',
          required: true,
        },
        {
          id: 'nativeplace',
          label: '籍贯',
          type: 'picker',
          required: true,
          cols: 1,
          data: areas,
          valueFormat: 'string', // string/array
        },
        {
          id: 'ethnic',
          label: '民族',
          type: 'picker',
          required: true,
          data: ethnics,
          cols: 1,
          valueFormat: 'string',
        },
        {
          id: 'occupation',
          label: '职业',
          type: 'picker',
          required: true,
          cols: 1,
          data: profession,
          valueFormat: 'string',
        },
        {
          id: 'maritalStatus',
          label: '婚姻状态',
          type: 'picker',
          cols: 1,
          required: true,
          data: maritalstatus,
          valueFormat: 'number',
        },
      ]
    },
    {
      id: 'part-3',
      desc: '伴侣基本信息',
      children: [
        {
          id: 'partnerName',
          label: '伴侣姓名',
          type: 'text-input',
          charactertype: 'text',
          required: true,
        },
        {
          id: 'partnerTelephone',
          label: '伴侣电话',
          type: 'text-input',
          charactertype: 'phone',
          required: true,
        },
        {
          id: 'partnerIdType',
          label: '伴侣证件类型',
          type: 'picker',
          required: true,
          cols:1,
          data: IDType,
          valueFormat: 'number',
        },
        {
          id: 'partnerIdNO',
          label: '伴侣证件号码',
          type: 'text-input',
          charactertype: 'text',
          required: true,
        },
        {
          id: 'partnerDob',
          label: '伴侣出生日期',
          type: 'date-picker',
          required: true,
          mode: 'date',
          format: 'YYYY-MM-DD',
          minDate: new Date(1960, 1, 1, 0, 0, 0),
          maxDate: new Date()
        },
        {
          id: 'partnerAge',
          label: '伴侣年龄',
          type: 'text-input',
          charactertype: 'digit',
          required: true,
        },
        {
          id: 'partnerNationality',
          label: '伴侣国籍',
          type: 'text-input',
          charactertype: 'text',
          required: true,
        },
        {
          id: 'partnerNativeplace',
          label: '伴侣籍贯',
          type: 'picker',
          required: true,
          cols: 1,
          data: areas,
          valueFormat: 'string',
        },
        {
          id: 'partnerEthnic',
          label: '伴侣民族',
          type: 'picker',
          required: true,
          cols: 1,
          data: ethnics,
          valueFormat: 'string',
        },
        {
          id: 'partnerOccupation',
          label: '伴侣职业',
          type: 'picker',
          required: true,
          cols: 1,
          data: profession,
          valueFormat: 'string',
        },
      ]
    },
    {
      id: 'part-4',
      desc: '地址信息',
      children: [
        {
          id: 'registeredAddress',
          label: '户口地址',
          type: 'address-picker',
          valueFormat: 'string',
          required: true,
        },
        {
          id: 'registeredAddressDetail',
          label: '户口详细地址',
          type: 'textarea-input',
          required: true,
        },
        {
          id: 'residenceAddress',
          label: '居住地址',
          type: 'address-picker',
          valueFormat: 'string',
          required: true,
        },
        {
          id: 'residenceAddressDetail',
          label: '居住详细地址',
          type: 'textarea-input',
          required: true,
        },
        {
          id: 'postpartumAddress',
          label: '产休地址',
          type: 'textarea-input',
          required: true,
        },
      ]
    },
  ],
};

export const pregnancy = {
  description: '本孕信息',
  data: [
    {
      id: 'part-1',
      desc: '信息块1',
      children: [
        {
          id: 'gravidity',
          label: '孕次',
          type: 'stepper-input',
          required: true,
          min: 0,
          max: 10,
        },
        {
          id: 'parity',
          label: '产次',
          type: 'stepper-input',
          required: true,
          min: 0,
          max: 10,
        },
      ],
    },
    {
      id: 'part-2',
      desc: '信息块2',
      children: [
        {
          id: 'lmp',
          label: '末次月经',
          type: 'date-picker',
          required: true,
          mode: 'date', // 日期date,时间time,日期+时间datetime,年year,月month
          format: 'YYYY-MM-DD',
        },
        {
          id: 'gestationalWeek',
          label: '孕周',
          type: 'text-input',
          charactertype: 'text',
          required: true,
        },
        {
          id: 'edd',
          label: '预产期',
          type: 'date-picker',
          required: true,
          mode: 'date',
          format: 'YYYY-MM-DD',
        },
        {
          id: 'sureEdd',
          label: '修订预产期',
          type: 'date-picker',
          required: true,
          mode: 'date',
          format: 'YYYY-MM-DD',
        },
      ],
    },
    {
      id: 'part-3',
      desc: '信息块3',
      children: [
        {
          id: 'pregnancyWeight',
          label: '孕前体重',
          type: 'text-input',
          suffix: 'kg',
          charactertype: 'digit',
          required: true,
        },
        {
          id: 'weight',
          label: '现在体重',
          type: 'text-input',
          suffix: 'kg',
          charactertype: 'digit',
          required: true,
        },
        {
          id: 'height',
          label: '身高',
          type: 'text-input',
          suffix: 'cm',
          charactertype: 'digit',
          required: true,
        },
        {
          id: 'systolicPressure',
          label: '收缩压',
          type: 'text-input',
          suffix: 'mmHg',
          charactertype: 'digit',
          required: true,
        },
        {
          id: ' diastolicPressure',
          label: '舒张压',
          type: 'text-input',
          suffix: 'mmHg',
          charactertype: 'digit',
          required: true,
        },
        {
          id: 'pulse',
          label: '脉搏',
          type: 'text-input',
          suffix: '次/分',
          charactertype: 'digit',
          required: true,
        },
      ],
    },
    {
      id: 'part-4',
      desc: '信息块4',
      children: [
        {
          id: 'yjcuch',
          label: '初潮',
          type: 'text-input',
          charactertype: 'digit',
          required: true,
        },
        {
          id: 'yjzhouq',
          label: '月经周期',
          type: 'text-input',
          suffix: '天',
          charactertype: 'digit',
          required: true,
        },
        {
          id: 'yjchix',
          label: '月经持续',
          type: 'text-input',
          suffix: '天',
          charactertype: 'digit',
          required: true,
        },
        {
          id: 'yjjingl',
          label: '经量多少',
          type: 'radio',
          charactertype: 'string',
          required: true,
          data: ['多', '中', '少'].map(e => ({ label: e, value: e })),
        },
        {
          id: 'yjtongj',
          label: '是否痛经',
          type: 'radio',
          charactertype: 'string',
          required: true,
          data: ['经常', '偶尔', '无'].map(e => ({ label: e, value: e })),
        },
        {
          id: 'smoke',
          label: '嗜好-烟',
          type: 'radio',
          charactertype: 'boolean',
          required: true,
          data: [{ label: '有', value: true }, { label: '无', value: false }],
        },
        {
          id: 'smokeNote',
          label: '每天吸烟量',
          suffix: '支/天',
          type: 'text-input',
          charactertype: 'digit',
          required: true,
        },
        {
          id: 'alcohol',
          label: '嗜好-酒',
          type: 'mix-picker',
          multiple: true,
          required: true,
          data: ['无', '白酒', '啤酒', '葡萄酒', '药酒'],
        },
        {
          id: 'alcoholNote',
          label: '饮酒量',
          suffix: 'ml/天',
          type: 'text-input',
          charactertype: 'digit',
          required: true,
        },
      ],
    },
    {
      id: 'part-5',
      desc: '信息块5',
      children: [
        {
          id: 'maritalYears',
          label: '结婚年龄',
          suffix: '岁',
          type: 'text-input',
          charactertype: 'digit',
          required: true,
        },
        {
          id: 'nearRelation',
          label: '是否近亲',
          type: 'radio',
          charactertype: 'boolean',
          required: true,
          data: [{ label: '是', value: true }, { label: '否', value: false }],
        },
        {
          id: 'partnerCigarette',
          label: '伴侣嗜好-烟',
          suffix: '支/天',
          type: 'text-input',
          charactertype: 'digit',
          required: true,
        },
        {
          id: 'partnerLiquor',
          label: '伴侣嗜好-酒',
          type: 'mix-picker',
          multiple: true,
          required: true,
          data: ['无', '白酒', '啤酒', '葡萄酒', '药酒'],
        },
        {
          id: 'partnerLiquorCapacity',
          label: '伴侣饮酒量',
          suffix: 'ml/天',
          type: 'text-input',
          charactertype: 'digit',
          required: true,
        },
        {
          id: 'partnerDiseaseHistory',
          label: '伴侣疾病史',
          type: 'mix-picker',
          multiple: true,
          required: true,
          data: [
            '无',
            '高血压',
            '糖尿病',
            '心脏病',
            '肝脏疾病',
            '肾脏疾病',
            '脑梗',
            '脑出血',
            '癌症',
            '哮喘',
            '肺结核',
            '甲亢',
            '过敏性疾病',
            '癫痫病',
            '风湿',
            '贫血',
            '地中海贫血',
            '癫痫',
            '近视',
          ],
        },
      ],
    },
    {
      id: 'part-6',
      desc: 'part-6',
      children: [
        {
          id: 'diseaseHistory',
          label: '疾病史',
          type: 'mix-picker',
          multiple: true,
          required: true,
          data: [
            '无',
            '妊娠糖尿病',
            'G6PD',
            '高血压',
            '糖尿病',
            '心脏病',
            '肝脏疾病',
            '肾脏疾病',
            '脑梗',
            '脑出血',
            '癌症',
            '哮喘',
            '肺结核',
            '甲亢',
            '过敏性疾病',
            '癫痫病',
            '风湿',
            '贫血',
            '地中海贫血',
            '癫痫',
            '近视',
          ],
        },
        {
          id: 'allergyHistory',
          label: '过敏史',
          type: 'mix-picker',
          multiple: true,
          required: true,
          data: ['无', '青霉素', '头孢', '磺胺类', '酒精', '食物过敏'],
        },
        {
          id: 'familyHistory',
          label: '家庭病史',
          type: 'mix-picker',
          multiple: true,
          required: true,
          data: [
            '无',
            '双胎',
            '死胎',
            '死产',
            '畸形',
            '遗传病',
            '精神病',
            '痴呆',
            '先天智力低下',
            '肿瘤',
            '糖尿病',
            '高血压',
            '高血脂',
            '肝炎',
            '甲亢',
            'G6PD',
            '肺结咳',
          ],
        }
      ],
    }
  ],
};

export const history = {
  description: '孕产史信息',
  data: [
    {
       id: 'part-6',
      desc: 'part-6',
      children: [
        {
          id: 'deliveryTime',
          label: '妊娠终止时间',
          type: 'date-picker',
          required: true,
          mode: 'date',
          format: 'YYYY-MM-DD',
        },
        {
          id: 'complication',
          label: '并发症',
          type: 'mix-picker',
          multiple: true,
          required: true,
          data: ['无', '妊娠期高血压', '妊娠期糖尿病', '前置胎盘', '巨大儿', '妊娠期肝内胆汁淤积症', '不记得'],
        },
        {
          id: 'isChildbirth',
          label: '是否分娩',
          type: 'radio',
          required: true,
          data: ['是', '否'].map(e => ({ label: e, value: e })),
        },
        {
          id: 'hospital',
          label: '分娩医院',
          type: 'text-input',
          charactertype: 'text',
          required: true,
          hide: true
        },
        {
          id: 'gestationalWeek',
          label: '分娩孕周',
          type: 'text-input',
          charactertype: 'text',
          required: true,
          hide: true
        },
        {
          id: 'fetusNumber',
          label: '胎数',
          type: 'stepper-input',
          required: true,
          min: 1,
          max: 6,
          hide: true
        },
        {
          id: 'abortion',
          label: '流产方式',
          type: 'picker',
          required: true,
          hide: true,
          cols: 1,
          data: ['自然', '人工', '引产', '生化', '胎停'].map(e => ({ label: e, value: e })),
        },
        {
          id: 'currettage',
          label: '清宫',
          type: 'radio',
          required: true,
          hide: true,
          data: ['是', '否'].map(e => ({ label: e, value: e })),
        },
        {
          id: 'unhealth',
          label: '不良生育史',
          type: 'picker',
          required: true,
          cols: 1,
          data: ['异位妊娠', '葡萄糖等滋养细胞疾病', '胚胎停育', '胎儿畸形', '死胎', '死产', '不清楚'].map(e => ({ label: e, value: e }))
        },
        {
          id: 'deliveryWay',
          label: '分娩方式',
          type: 'picker',
          required: true,
          hide: true,
          cols: 1,
          data: ['顺产', '剖宫产', '吸引', '钳产', '臀助产'].map(e => ({ label: e, value: e }))
        },
        {
          id: 'fever',
          label: '产后发热',
          type: 'radio',
          required: true,
          hide: true,
          data: ['是', '否'].map(e => ({ label: e, value: e })),
        },
        {
          id: 'hemorrhage',
          label: '产后出血',
          type: 'radio',
          required: true,
          hide: true,
          data: ['是', '否'].map(e => ({ label: e, value: e })),
        },
      ]
    }
  ]
}
