export const ENTRANCE = [
         {
           key: '1',
           label: '围产档案',
           icon: 'i1.png',
           route: '/perinatal/list',
           color: 'linear-gradient(-45deg, #FFBFD9 0%, #FF6B70 100%)',
         },
         {
           key: '2',
           label: '产检记录',
           icon: 'i2.png',
           route: '',
           color: 'linear-gradient(-45deg, #FFD52B 0%, #FFA002 100%)',
         },
         {
           key: '3',
           label: '远程监护',
           icon: 'i8.png',
           route: '',
           color: 'linear-gradient(-45deg, #3BF7FF 0%, #00B9FF 100%)',
         },
         {
           key: '4',
           label: '套餐服务',
           icon: 'i7.png',
           route: '/order',
           color: 'linear-gradient(-45deg, #FFBA8D 0%, #FF7D34 100%)',
         },
         {
           key: '5',
           label: '电子报告',
           icon: 'i5.png',
           route: '/reports/list',
           color: 'linear-gradient(-45deg, #FFC4EF 0%, #FF445B 100%)',
         },
         {
           key: '6',
           label: '孕妇学校',
           icon: 'i6.png',
           route: '/school?type=article',
           color: 'linear-gradient(-45deg, #FFC4EF 0%, #FF445B 100%)',
         },
         {
           key: '7',
           label: '随访记录',
           icon: 'i1.png',
           route: '',
           color: 'linear-gradient(-45deg, #FFC4EF 0%, #FF445B 100%)',
         },
         {
           key: '8',
           label: '在线咨询',
           icon: 'i3.png',
           route: '/consultation',
           color: '',
         },
         {
           key: '88',
           label: '我的订单',
           icon: 'i4.png',
           route: '/myorder',
           color: '',
         },
         {
           key: '9',
           label: 'h5支付',
           icon: 'i1.png',
           route: '/webtest',
           color: 'linear-gradient(-45deg, #FFC4EF 0%, #FF445B 100%)',
         },
       ];

export const TOOLS = [
         {
           key: '1',
           label: '体重管理',
           icon: 'i001.png',
           route: '/weight/input',
         },
         {
           key: '2',
           label: '血糖管理',
           icon: 'i002.png',
           route: '',
         },
         {
           key: '3',
           label: '血压管理',
           icon: 'i007.png',
           route: '',
         },
         {
           key: '4',
           label: '胎动计数',
           icon: 'i003.png',
           route: '',
         },
         {
           key: '5',
           label: '我的收藏',
           icon: 'i004.png',
           route: '',
         },
         {
           key: '6',
           label: '我的提醒',
           icon: 'i005.png',
           route: '',
         },
         {
           key: '7',
           label: '其他',
           icon: 'i006.png',
           route: '',
         },
         {
           key: '8',
           label: '其他',
           icon: 'i008.png',
           route: '',
         },
       ];
